export const RECEIVE_SEO_SETTINGS = 'boilerplate/user/RECEIVE_SEO_SETTINGS';
export const RECEIVE_SEO_SETTINGS_ERROR =
  'boilerplate/user/RECEIVE_SEO_SETTINGS_ERROR';
export const SAVE_SEO_SETTINGS = 'boilerplate/user/SAVE_SEO_SETTINGS';
export const FETCH_SEO_SETTINGS = 'boilerplate/user/FETCH_SEO_SETTINGS';

export default {
  RECEIVE_SEO_SETTINGS,
  RECEIVE_SEO_SETTINGS_ERROR,
  SAVE_SEO_SETTINGS,
  FETCH_SEO_SETTINGS,
};
