export const AUTH_CHECK = 'AUTH_CHECK';
export const LOAD_USER_REQUEST = 'boilerplate/user/LOAD_USER_REQUEST';
export const LOAD_USER_ERROR = 'boilerplate/user/LOAD_USER_ERROR';
export const LOAD_USER_SUCCESS = 'boilerplate/user/LOAD_USER_SUCCESS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS_RESPONSE = 'LOGIN_SUCCESS_RESPONSE';
export const LOGIN_FAILURE_RESPONSE = 'LOGIN_FAILURE_RESPONSE';
export const LOGOUT_USER_SUCCESS = 'boilerplate/user/LOGOUT_USER_SUCCESS';
export const RECEIVE_USER = 'boilerplate/user/RECEIVE_USER';
export const RECEIVE_USER_ERROR = 'boilerplate/user/RECEIVE_USER_ERROR';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_SUCCESS_RESPONSE = 'SIGNUP_SUCCESS_RESPONSE';
export const SIGNUP_FAILURE_RESPONSE = 'SIGNUP_FAILURE_RESPONSE';
export const SOCIAL_SIGNUP_REQUEST = 'SOCIAL_SIGNUP_REQUEST';
export const SOCIAL_USER_RECEIVED = 'SOCIAL_USER_RECEIVED';

export default {
  AUTH_CHECK,
  LOAD_USER_REQUEST,
  LOAD_USER_ERROR,
  LOAD_USER_SUCCESS,
  LOGIN_REQUEST,
  LOGIN_SUCCESS_RESPONSE,
  LOGIN_FAILURE_RESPONSE,
  LOGOUT_USER_SUCCESS,
  RECEIVE_USER,
  RECEIVE_USER_ERROR,
  SIGNUP_REQUEST,
  SIGNUP_SUCCESS_RESPONSE,
  SIGNUP_FAILURE_RESPONSE,
  SOCIAL_SIGNUP_REQUEST,
  SOCIAL_USER_RECEIVED,
};
